#version: '3.5'
#services:
#  redis:
#    image: redis:6.2-alpine
#    restart: always
#    ports:
#      - '6380:6380'
#    volumes:
#      - cache:/data
#
#  db:
#    image: mysql
#    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
#    # (this is just an example, not intended to be a production configuration)
#    command: --default-authentication-plugin=mysql_native_password
#    restart: always
#    ports:
#      - "3307:3307"
#    environment:
#      MYSQL_ROOT_PASSWORD: password
#      MYSQL_DATABASE: kinorium
#      MYSQL_USER: practice
#      MYSQL_USER_PASSWORD: password
#      MYSQL_ROOT_HOSTS: '%'
#
#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - "8081:8081"
#
#volumes:
#  cache:
#    driver: local